[prune]
  unused-packages = true
  go-tests = true
  non-go = true
    [[prune.project]]
    name = "github.com/hyperledger/burrow"
    unused-packages = false
    non-go = false

[[override]]
  name = "github.com/hyperledger/burrow"
  revision = "ea957bdae632ab61dcf24e6c4673f05bb7c66681"

# We don't care which version Tendermint wants
[[override]]
  name = "github.com/tendermint/tendermint"
  version = "=0.22.4"

[[override]]
  name = "github.com/gogo/protobuf"
  version = "~1.1.0"

[[override]]
  name = "github.com/golang/protobuf"
  version = "~1.1.0"

[[override]]
  name = "google.golang.org/grpc"
  version = "~1.13.0"
