[prune]
  unused-packages = true
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "github.com/ethereum/go-ethereum"
    # Otherwise secp256k1.h excluded and test compile fails
    unused-packages = false
    non-go = false

[[constraint]]
  name = "github.com/hyperledger/burrow"
  branch = "develop"

# Geth version we currently depend on for ABI
[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "=1.6.1"
