[prune]
  unused-packages = true
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "github.com/ethereum/go-ethereum"
    # Otherwise secp256k1.h excluded and test compile fails
    unused-packages = false
    non-go = false

[[constraint]]
  name = "github.com/hyperledger/burrow"
  branch = "event-state"

# Geth version we currently depend on for ABI
[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "=1.6.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "~1.0.5"

# We don't care which version Tendermint wants
[[override]]
  name = "github.com/tendermint/tmlibs"
  version = "~0.8.4"

[[override]]
  name = "github.com/golang/protobuf"
  version = "~1.1.0"

[[override]]
  name = "google.golang.org/grpc"
  version = "~1.12.2"
