# Some resuable sections, note the top-level keys 'defaults' and 'tag_filters'
# have no special meaning, they just exist so I can alias them and import them
# in later blocks
defaults: &defaults
  working_directory: /go/src/github.com/monax/bosmarmot
  docker:
    - image: quay.io/monax/bosmarmot:ci

tag_filters: &tags_filters
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

# Start of CircleCI 2.0 config
version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: make npm_install
      - run: make test

  test_integration:
    <<: *defaults
    steps:
      - checkout
      - run: make npm_install
      - run: make test_integration

  ensure_vendor:
    <<: *defaults
    steps:
      - checkout
      - run: make ensure_vendor

  publish_npm:
    <<: *defaults
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
      - run: cd legacy-db.js && npm publish
      - run: cd legacy-contracts.js && npm publish


workflows:
  version: 2

  test_and_release:
    jobs:
      - test:
          filters:
            <<: *tags_filters

      - test_integration:
          filters:
            <<: *tags_filters

      - ensure_vendor:
          filters:
            <<: *tags_filters

      - publish_npm:
          requires:
            - test
            - test_integration
            - ensure_vendor
          filters:
            <<: *tags_filters
            branches:
              ignore: /.*/
