# Some resuable sections, note the top-level keys 'defaults' and 'tag_filters'
# have no special meaning, they just exist so I can alias them and import them
# in later blocks
defaults: &defaults
  working_directory: /go/src/github.com/monax/bosmarmot
  docker:
    - image: quay.io/monax/bosmarmot:ci

# Start of CircleCI 2.0 config
version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: make test

  test_integration:
    <<: *defaults
    steps:
      - checkout
      - run: make test_integration

  ensure_vendor:
    <<: *defaults
    steps:
      - checkout
      - run: make ensure_vendor
  
  #publish_npm:
    #docker:
    #  - image: circleci/<language>:<version TAG>
    #steps:
    #  - checkout
    #  - run: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" >> ~/.npmrc
    #  - run: npm publish

workflows:

  version: 2
  test_and_release:
    jobs:
      - test
      - test_integration
      - ensure_vendor

