# Some resuable sections, note the top-level keys 'defaults' and 'tag_filters'
# have no special meaning, they just exist so I can alias them and import them
# in later blocks
defaults: &defaults
  working_directory: /go/src/github.com/monax/bosmarmot
  docker:
    - image: circleci/golang:1.9.3

# Start of CircleCI 2.0 config
version: 2
jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: make test

  test_solc_latest:
    <<: *defaults
    steps:
      - checkout
      - run:
          # note the compiler tests need to be reworked/removed with solc >0.4.20
          command: |
            make test_solc_latest || true

  test_integration:
    <<: *defaults
    steps:
      - checkout
      - run: make test_integration

  test_integration_solc_latest:
    <<: *defaults
    steps:
      - checkout
      - run:
          command: |
            make test_integration_solc_latest

  ensure_vendor:
    <<: *defaults
    steps:
      - checkout
      - run: make ensure_vendor

workflows:

  version: 2
  test_and_release:
    jobs:
      - test
      - test_integration
      - test_solc_latest
      - test_integration_solc_latest
      - ensure_vendor

